spring:
  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#          storage_engine: innodb

  session:
    store-type: jdbc

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  dir: /home/ec2-user/app/images
